### ISSUE TITLE
Generated parsers as library dependencies

### ISSUE THREAD

**Issue by bennostein** [returntocorp/ocaml-tree-sitter-languages#1]
Is there an established/recommended workflow for using a parser generated by this tool as a library dependency in a different project?

I have things set up for now as follows (using e.g. `ruby`):
 1. `./scripts/rebuild-everything`
 2. `cd lang ; ./test-lang ruby ; cd ruby/ocaml-src/lib`
 3. write the following barebones opam config to `tree_sitter_ruby.opam`:
  ```
opam-version: "2.0"
maintainer: "none; generated code"
build: [["dune" "build" "-p" name "-j" jobs]]
synopsis: "code generated by github.com/returntocorp/ocaml-tree-sitter"
depends: []
  ```
4. `sed -i "" "s/tree-sitter-lang.ruby/tree_sitter_ruby/" dune`
5. `dune build --root .`
6. `opam pin add -y tree_sitter_ruby .`

such that other local projects can now specify a dependency on `tree_sitter_ruby` in the `libraries` field of their `dune` config.  This works well-enough for local development but feels a bit brittle and maybe ill-advised.

I have a couple related questions on this setup:
1. Are the above steps a reasonable way to go about this, or would you recommend a different approach partially/entirely?
2. Would you be open to upstreaming some documentation and/or scripts to support this use-case if I were to write those?  If so, I'd be happy to discuss further and/or revise the hacky process detailed here as you see fit.

Thanks in advance for your time and for the great tool!

**Comment by mjambon** [comment]
I'm closing this. I created a couple issues for related tasks. Feel free to create more.
